### PR TITLE
Icon test

### PR DESCRIPTION
**Pull request by ksobon**
I added an icon to match that in Grasshopper. It has that circle with a white background around it because just a plain black hydra logo is almost invisible on the dark Dynamo background. No white background works in Grasshopper since it has a light grey color for components.

### CODE REVIEW

**Comment by ksobon** [comment]
untitled-1

This is what it looks like in Dynamo

**Comment by mostaphaRoudsari** [comment]
Thanks @ksobon!

**Comment by alfarok** [comment]
@ksobon This is awesome!  I am probably doing something wrong but I am having trouble getting it to load on my local build.  I cloned the repo and made sure all the resource files are loading but still get the default Dynamo icon.

**Comment by ksobon** [comment]
@alfarok check your Hydra.csproj file and make sure that you got the "before buid" set up like this: 

``` html
<Target Name="BeforeBuild">
<GetReferenceAssemblyPaths TargetFrameworkMoniker=".NETFramework, Version=v2.0">
      <Output TaskParameter="FullFrameworkReferenceAssemblyPaths" PropertyName="FrameworkAssembliesPath" />
    </GetReferenceAssemblyPaths>
    <GenerateResource UseSourcePath="true" Sources="$(ProjectDir)SampleLibraryUIImages.resx" OutputResources="$(ProjectDir)SampleLibraryUIImages.resources" References="$(FrameworkAssembliesPath)System.Drawing.dll" />
    <AL TargetType="library" EmbedResources="$(ProjectDir)SampleLibraryUIImages.resources" OutputAssembly="$(OutDir)SampleLibraryUI.customization.dll" />
  </Target>
```

**Comment by alfarok** [comment]
@ksobon now I am getting an error when compiling that SampleLibraryUIImages.resx cannot be found

**Comment by alfarok** [comment]
@ksobon got it!

**Comment by ksobon** [comment]
There is a sequence to it. You first need to add the resex to the solution. build it. then edit the cs proj and when you go back to visual studio (you never close visual studio), it will ask you to reload all so just confirm. then build it again. 

Now, that you are getting that error, remove the before build from cs proj and rebuild. Then just follow the step above.

**Comment by alfarok** [comment]
I spoke too soon, I am still failing lol.

Here is exactly what I am doing:
1) Open visual studio project file
2) Create SampleLibraryUIImages.resx
3) Clear custom tool option in the properties window
4) Drag the 2 resources images into the .resx file (small and large pngs)
5) In properties change persistence to embedded in .resx for both pngs
6) Rebuild the solution
7) Open Hydra.csproj in notepad++ and add the build before text referenced above
8) I reloaded the file when prompted in visual studio and rebuild
9) Replace the old hydra bin folder with the new one

Sorry for all the confusion @ksobon 
I used [this](https://github.com/DynamoDS/Dynamo/wiki/Creating-Icons-for-Custom-Nodes) as a reference

**Comment by ksobon** [comment]
@alfarok no worries we will sort this out. I wouldn't use the link you attached because that's for Custom Nodes that were not compiled but created using the UI method. Use this instead: 

https://github.com/DynamoDS/Dynamo/wiki/Add-Icons-for-a-Zero-Touch-Assembly

**Comment by alfarok** [comment]
Well, I found my mistake...the SampleLibraryUI.customization.dll was copying to a different bin folder then the rest of the dll's ಠ_ಠ

**Pull request merged**
